# apiVersion: v1
# kind: Service
# metadata:
#   name: rollouts-demo
# spec:
#   ports:
#   - port: 80
#     targetPort: http
#     protocol: TCP
#     name: http
#   selector:
#     app: rollouts-demo

apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: rollouts-demo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollouts-demo
  service:
    port: 80
    targetPort: 8080
  analysis:
    interval: 1m
    # max number of failed metrics to rollback
    threshold: 5
    # max percent of traffic to canary
    maxWeight: 100
    # weight of each steps
    stepWeight: 20
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m